//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.dfdsfdbfghh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Resource.
    /// </summary>
    //  *** Start programmer edit section *** (resource CustomAttributes)

    //  *** End programmer edit section *** (resource CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("resourceE", new string[] {
            "name as \'Name\'",
            "description as \'Description\'",
            "external_id as \'External_id\'",
            "cfs_id as \'Cfs_id\'",
            "cfs_id.name as \'Name\'",
            "parent_service_id as \'Parent_service_id\'",
            "parent_service_id.name as \'Name\'",
            "resource_shared_id as \'Resource_shared_id\'",
            "resource_shared_id.external_id as \'External_id\'",
            "resource_spec_id as \'Resource_spec_id\'",
            "resource_spec_id.enum as \'Enum\'",
            "customer_id as \'Customer_id\'",
            "customer_id.customer as \'Customer\'",
            "contragent_id as \'Contragent_id\'",
            "contragent_id.contragent as \'Contragent\'",
            "cfs_id as \'Cfs_id\'",
            "cfs_id.name as \'Name\'",
            "resource_spec_id as \'Resource_spec_id\'",
            "resource_spec_id.enum as \'Enum\'",
            "parent_id as \'Parent_id\'",
            "parent_id.name as \'Name\'",
            "resource_shared_id as \'Resource_shared_id\'",
            "resource_shared_id.external_id as \'External_id\'"})]
    [View("resourceL", new string[] {
            "name as \'Name\'",
            "description as \'Description\'",
            "external_id as \'External_id\'",
            "cfs_id as \'Name\'",
            "parent_service_id as \'Name\'",
            "resource_shared_id as \'External_id\'",
            "resource_spec_id as \'Enum\'",
            "customer_id as \'Customer\'",
            "contragent_id as \'Contragent\'",
            "cfs_id as \'Name\'",
            "resource_spec_id as \'Enum\'",
            "parent_id as \'Name\'",
            "resource_shared_id as \'External_id\'"}, Hidden=new string[] {
            "cfs_id",
            "parent_service_id",
            "resource_shared_id",
            "resource_spec_id",
            "customer_id",
            "contragent_id",
            "cfs_id",
            "resource_spec_id",
            "parent_id",
            "resource_shared_id"})]
    public class resource : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fdescription;
        
        private string fexternal_id;
        
        private DataLine.dfdsfdbfghh.service fparent_service_id;
        
        private DataLine.dfdsfdbfghh.contragent fcontragent_id;
        
        private DataLine.dfdsfdbfghh.resource fparent_id;
        
        private DataLine.dfdsfdbfghh.resource_spec fresource_spec_id;
        
        private DataLine.dfdsfdbfghh.service fcfs_id;
        
        private DataLine.dfdsfdbfghh.resource_shared fresource_shared_id;
        
        private DataLine.dfdsfdbfghh.customer fcustomer_id;
        
        //  *** Start programmer edit section *** (resource CustomMembers)

        //  *** End programmer edit section *** (resource CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (resource.name CustomAttributes)

        //  *** End programmer edit section *** (resource.name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (resource.name Get start)

                //  *** End programmer edit section *** (resource.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (resource.name Get end)

                //  *** End programmer edit section *** (resource.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.name Set start)

                //  *** End programmer edit section *** (resource.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (resource.name Set end)

                //  *** End programmer edit section *** (resource.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (resource.description CustomAttributes)

        //  *** End programmer edit section *** (resource.description CustomAttributes)
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (resource.description Get start)

                //  *** End programmer edit section *** (resource.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (resource.description Get end)

                //  *** End programmer edit section *** (resource.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.description Set start)

                //  *** End programmer edit section *** (resource.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (resource.description Set end)

                //  *** End programmer edit section *** (resource.description Set end)
            }
        }
        
        /// <summary>
        /// external_id.
        /// </summary>
        //  *** Start programmer edit section *** (resource.external_id CustomAttributes)

        //  *** End programmer edit section *** (resource.external_id CustomAttributes)
        [StrLen(128)]
        public virtual string external_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.external_id Get start)

                //  *** End programmer edit section *** (resource.external_id Get start)
                string result = this.fexternal_id;
                //  *** Start programmer edit section *** (resource.external_id Get end)

                //  *** End programmer edit section *** (resource.external_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.external_id Set start)

                //  *** End programmer edit section *** (resource.external_id Set start)
                this.fexternal_id = value;
                //  *** Start programmer edit section *** (resource.external_id Set end)

                //  *** End programmer edit section *** (resource.external_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.parent_service_id CustomAttributes)

        //  *** End programmer edit section *** (resource.parent_service_id CustomAttributes)
        [PropertyStorage(new string[] {
                "parent_service_id"})]
        public virtual DataLine.dfdsfdbfghh.service parent_service_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.parent_service_id Get start)

                //  *** End programmer edit section *** (resource.parent_service_id Get start)
                DataLine.dfdsfdbfghh.service result = this.fparent_service_id;
                //  *** Start programmer edit section *** (resource.parent_service_id Get end)

                //  *** End programmer edit section *** (resource.parent_service_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.parent_service_id Set start)

                //  *** End programmer edit section *** (resource.parent_service_id Set start)
                this.fparent_service_id = value;
                //  *** Start programmer edit section *** (resource.parent_service_id Set end)

                //  *** End programmer edit section *** (resource.parent_service_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.contragent_id CustomAttributes)

        //  *** End programmer edit section *** (resource.contragent_id CustomAttributes)
        [PropertyStorage(new string[] {
                "contragent_id"})]
        public virtual DataLine.dfdsfdbfghh.contragent contragent_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.contragent_id Get start)

                //  *** End programmer edit section *** (resource.contragent_id Get start)
                DataLine.dfdsfdbfghh.contragent result = this.fcontragent_id;
                //  *** Start programmer edit section *** (resource.contragent_id Get end)

                //  *** End programmer edit section *** (resource.contragent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.contragent_id Set start)

                //  *** End programmer edit section *** (resource.contragent_id Set start)
                this.fcontragent_id = value;
                //  *** Start programmer edit section *** (resource.contragent_id Set end)

                //  *** End programmer edit section *** (resource.contragent_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.parent_id CustomAttributes)

        //  *** End programmer edit section *** (resource.parent_id CustomAttributes)
        [PropertyStorage(new string[] {
                "parent_id"})]
        public virtual DataLine.dfdsfdbfghh.resource parent_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.parent_id Get start)

                //  *** End programmer edit section *** (resource.parent_id Get start)
                DataLine.dfdsfdbfghh.resource result = this.fparent_id;
                //  *** Start programmer edit section *** (resource.parent_id Get end)

                //  *** End programmer edit section *** (resource.parent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.parent_id Set start)

                //  *** End programmer edit section *** (resource.parent_id Set start)
                this.fparent_id = value;
                //  *** Start programmer edit section *** (resource.parent_id Set end)

                //  *** End programmer edit section *** (resource.parent_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.resource_spec_id CustomAttributes)

        //  *** End programmer edit section *** (resource.resource_spec_id CustomAttributes)
        [PropertyStorage(new string[] {
                "resource_spec_id"})]
        [NotNull()]
        public virtual DataLine.dfdsfdbfghh.resource_spec resource_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.resource_spec_id Get start)

                //  *** End programmer edit section *** (resource.resource_spec_id Get start)
                DataLine.dfdsfdbfghh.resource_spec result = this.fresource_spec_id;
                //  *** Start programmer edit section *** (resource.resource_spec_id Get end)

                //  *** End programmer edit section *** (resource.resource_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.resource_spec_id Set start)

                //  *** End programmer edit section *** (resource.resource_spec_id Set start)
                this.fresource_spec_id = value;
                //  *** Start programmer edit section *** (resource.resource_spec_id Set end)

                //  *** End programmer edit section *** (resource.resource_spec_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.cfs_id CustomAttributes)

        //  *** End programmer edit section *** (resource.cfs_id CustomAttributes)
        [PropertyStorage(new string[] {
                "cfs_id"})]
        [NotNull()]
        public virtual DataLine.dfdsfdbfghh.service cfs_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.cfs_id Get start)

                //  *** End programmer edit section *** (resource.cfs_id Get start)
                DataLine.dfdsfdbfghh.service result = this.fcfs_id;
                //  *** Start programmer edit section *** (resource.cfs_id Get end)

                //  *** End programmer edit section *** (resource.cfs_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.cfs_id Set start)

                //  *** End programmer edit section *** (resource.cfs_id Set start)
                this.fcfs_id = value;
                //  *** Start programmer edit section *** (resource.cfs_id Set end)

                //  *** End programmer edit section *** (resource.cfs_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.resource_shared_id CustomAttributes)

        //  *** End programmer edit section *** (resource.resource_shared_id CustomAttributes)
        [PropertyStorage(new string[] {
                "resource_shared_id"})]
        public virtual DataLine.dfdsfdbfghh.resource_shared resource_shared_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.resource_shared_id Get start)

                //  *** End programmer edit section *** (resource.resource_shared_id Get start)
                DataLine.dfdsfdbfghh.resource_shared result = this.fresource_shared_id;
                //  *** Start programmer edit section *** (resource.resource_shared_id Get end)

                //  *** End programmer edit section *** (resource.resource_shared_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.resource_shared_id Set start)

                //  *** End programmer edit section *** (resource.resource_shared_id Set start)
                this.fresource_shared_id = value;
                //  *** Start programmer edit section *** (resource.resource_shared_id Set end)

                //  *** End programmer edit section *** (resource.resource_shared_id Set end)
            }
        }
        
        /// <summary>
        /// Resource.
        /// </summary>
        //  *** Start programmer edit section *** (resource.customer_id CustomAttributes)

        //  *** End programmer edit section *** (resource.customer_id CustomAttributes)
        [PropertyStorage(new string[] {
                "customer_id"})]
        [NotNull()]
        public virtual DataLine.dfdsfdbfghh.customer customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource.customer_id Get start)

                //  *** End programmer edit section *** (resource.customer_id Get start)
                DataLine.dfdsfdbfghh.customer result = this.fcustomer_id;
                //  *** Start programmer edit section *** (resource.customer_id Get end)

                //  *** End programmer edit section *** (resource.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource.customer_id Set start)

                //  *** End programmer edit section *** (resource.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (resource.customer_id Set end)

                //  *** End programmer edit section *** (resource.customer_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "resourceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resourceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resourceE", typeof(DataLine.dfdsfdbfghh.resource));
                }
            }
            
            /// <summary>
            /// "resourceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resourceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resourceL", typeof(DataLine.dfdsfdbfghh.resource));
                }
            }
        }
    }
}
